### ISSUE TITLE
Cookie session support

### ISSUE THREAD

**Issue by akelyasir** [zino-rs/zino#108]
Hi @photino 

Do you plan to support cookie sessions with JWT?

**Comment by photino** [comment]
Do you mean extracting the `access_token` from a cookie?

**Comment by akelyasir** [comment]
Hi @photino
Yes, there is no need for jwt to be used for user login. Will you support cookie session?

**Comment by photino** [comment]
We have the  [`get_cookie`](https://docs.rs/zino-core/latest/zino_core/request/trait.RequestContext.html#method.get_cookie) method to get a cookie.

Currently, we support extracting `access_token` from the query param and the `authorization` header. I am not sure whether we should support extracting it from a cookie directly.

**Comment by akelyasir** [comment]
Thank you for your answer. I asked for security. For example, if we need to create a management panel for the website, we will need to use localstorage for user login management. Would this be secure enough for the user? I thought maybe a little more security could be provided if it also supported cookies.

I am currently doing this with Zino using Actix Session. If I could provide a common solution to others, I would share it.

**Comment by photino** [comment]
localstorage is more secure than cookie to save a user token.

**Comment by akelyasir** [comment]
Thanks @photino
