### ISSUE TITLE
router为啥找不到啊

### ISSUE THREAD

**Issue by aohanhongzhi** [zino-rs/zino#109]
![img_v3_02bl_42e75f96-1449-4be3-afa3-a1e9db2ce94g](https://github.com/zino-rs/zino/assets/37319319/d9b7a01a-9381-41d4-a1d9-4224c815e705)
![img_v3_02bl_6627fc15-a5d2-46ff-87ba-1a269c69d55g](https://github.com/zino-rs/zino/assets/37319319/50ef8e52-7ff6-4ac6-84bd-c06e2359ffa4)
https://gitee.com/aohanhongzhi/rust-zino

**Comment by photino** [comment]
要使用 `register` 注册路由的
