### ISSUE TITLE
Password update question

### ISSUE THREAD

**Issue by akelyasir** [zino-rs/zino#128]
Hi @photino

When adding a new user, the specified password is correctly recorded in the database, that is, the encryption process works for the password field. However, the encryption process does not occur during the password update. Should we do this ourselves?

Thanks

**Comment by Klevente12** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by photino** [comment]
> Hi @photino
> 
> When adding a new user, the specified password is correctly recorded in the database, that is, the encryption process works for the password field. However, the encryption process does not occur during the password update. Should we do this ourselves?
> 
> Thanks

The default encryption scheme of password is provided by https://docs.rs/zino-core/latest/zino_core/orm/trait.ModelHelper.html#method.encrypt_password It is used when adding a new user if you does not handle the password encryption manually. For updating the password, you should call this method first before saving it to the database.
