### ISSUE TITLE
Use `serde_json::from_slice` instead of `serde_json::from_reader` to improve  performance

### ISSUE THREAD

**Issue by photino** [zino-rs/zino#13]
See [Parsing 20MB file using from_reader is slow](https://github.com/serde-rs/json/issues/160)

**Comment by colommar** [comment]
In fact, I didn't find it in the code.  Either `serde_json::from_slice` or `serde_json::from_reader`.
It's also possible that I'm missing your point.
Can you point out my misunderstanding?

**Comment by photino** [comment]
This is an old issue. 😄 It has already been replaced the new versions. Perhaps we should close this.
