### ISSUE TITLE
TraceLayer中间件日志中信息冗余

### ISSUE THREAD

**Issue by zelasier** [zino-rs/zino#133]
### 问题描述

在使用TraceLayer中间件时，每个请求的日志信息中包含大量重复和冗余的信息，运维时定位业务日志看的眼花，例如：

```
HTTP request{otel.kind="server" otel.name="iot-app" url.path="/iotapp/web/health/data/index" url.query="userToken=14F3E95E280E94F75D7EB2B24C22ECFA3F0D04F68EA2608F6783B874E4F50EEF&sdkProductId=10970&hhDeviceId=01927544-ef77-7170-a9f5-7ac0e00f90ce&realUserToken=14F3E95E280E94F75D7EB2B24C22ECFA3F0D04F68EA2608F6783B874E4F50EEF" http.request.method="GET" user_agent.original="Apifox/1.0.0 (https://apifox.com)" context.span_id="10000000015" context.request_id="0192c333-9670-7cb1-af74-71e1cde5d28e"}
```

### 期望行为

1、希望每个请求中只**打印一次path、query等信息**，并在后续日志中只保留`request_id`用于上下文追踪。

或者

2、希望提供禁用注册zino::middleware::TRACING_MIDDLEWARE的方式

### 重现步骤

1. 发起一个HTTP请求。
2. 查看生成的日志信息。

### 环境信息

- Rust版本：`1.8.1`
- Zino版本：`0.25.3`

### 其他信息
![20241025-183302](https://github.com/user-attachments/assets/f97da68d-a3ec-478a-a5c1-ce3e79020f2a)
```

**Comment by photino** [comment]
日志可以通过设置level或filter进行过滤以减少日志量 完全禁止的话 就是设置zino的`default-features = false`

**Comment by zelasier** [comment]
已解决😃. 通过filter过滤zino::middleware::tower_tracing
