### ISSUE TITLE
把项目拆分

### ISSUE THREAD

**Issue by chinaxxren** [zino-rs/zino#135]
我觉得项目太大的了，每个模块学习起来非常的多，我觉得你可以把项目中每个 lib 都单独拆成一个 crate 和一个例子，这样学习起来就很快，也免除各种没有必要的东西干扰！

**Comment by photino** [comment]
主要是拆分得多的话 维护成本就会提高 

不过我们的方向确实是要拆分，目前打算是先把zino中和不同框架的集成拆分到不同的crates，便于维护和扩展

**Comment by photino** [comment]
已经拆分出了 zino-auth 和 zino-http 后期会继续这个方向的工作
