### ISSUE TITLE
使用QueryBuilder或Query构建SQL时，当Value包含`null`、`,`等特定关键词时，会更改开发者原有的条件判断目的.

### ISSUE THREAD

**Issue by zelasier** [zino-rs/zino#139]
### 问题描述

在当前的代码实现中，我使用 `QueryBuilder` 来构建数据库查询，并使用 `find_one` 方法来格式化查询过滤器。
- 当 `platform_product_id` 的值包含逗号（`,`）时，例如苹果对iPhone13的编码定义：`APPLE-14,5`
- `query.format_filters::<Self>()` 方法会不正确地将其解析为 `IN ('APPLE-14', '5')`操作，导致无法查询到数据。
- 需要一种明确的方法来指定在 `query.format_filters::<Self>()` 中使用严格的 `eq` 操作符，而不对参数值进行解析。
- 期待能够优化 `query.format_filters::<Self>()` 的内部逻辑，以支持直接使用 `eq` 操作符。

```rust
pub(crate) async fn get_by_platform_product_id_op(
    platform: &String,
    platform_product_id: &String,
) -> Result<Option<IotProduct>, Error> {
    let query = QueryBuilder::<IotProduct>::new()
        .and_eq(Platform, platform.to_string())
        .and_eq(PlatformProductId, platform_product_id.to_string())
        .and_eq(IsExist, 1)
        .order_asc(Sort)
        .limit(1)
        .build();

    Ok(IotProduct::find_one(&query).await?)
}
```

### 期望的行为

- 希望在 `QueryBuilder` 中，能够提供机制选择在格式化过滤器时不对特定字段的值进行解析。
- 在 `platform_product_id` 包含特定字符（如逗号）时依然能够执行等值查询。
- 不再解析String类型的Value的任何特殊含义.

### 附加信息

- 希望能够收到对 `query.format_filters::<Self>()` 方法的修改或替代方案的建议。

### 

![解析操作符源码截图](https://github.com/user-attachments/assets/196b626e-b86e-45f4-bcee-533b129164f0)

**Comment by photino** [comment]
是有这个问题，多谢反馈！我们可能会考虑增加一个`eq_exact()`方法

**Comment by photino** [comment]
我们在zino-orm 0.2中为eq改用了精确过滤条件 之前的and_eq可以使用and_filter来使用默认处理 可以升级到最新的依赖试试
