### ISSUE TITLE
[example/dioxus-desktop] I had tested for stargazer, but when navigating and switching pages, the process exits unexpectedly 

### ISSUE THREAD

**Issue by beesflower** [zino-rs/zino#95]
thread 'main' panicked at dioxus-desktop/src/view/stargazer.rs:102:38:
called `Result::unwrap()` on an `Err` value: AlreadyBorrowed(AlreadyBorrowedError)

**Comment by photino** [comment]
It works as expected on my computer.

**Comment by photino** [comment]
It should be fixed in the latest version of the example.
